server:
  port: '8070'


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: jghan
    url: jdbc:mysql://localhost:3306/museumPJT?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    password: '0000'